#! /usr/bin/env python

# True false is not working >>> instead comment out the prog not used
# and remove last comma
REALUSER = "admin" #lara
JOB_NUM = "trial_new_release2"
DEBUG = True

para_dict = dict(
#################### TEST INPUT
file_read1 = "/home/cvcv/genorama/webserver/demo_data/reads_left.fq",
file_read2 = "/home/cvcv/genorama/webserver/demo_data/reads_right.fq",
#file_ass = "/home/cvcv/genorama/webserver/demo_data/Trinity.fasta",
input_type = "paired",
#################### INPUT
#file_read1 = "/home/cvcv/genorama/webserver/demo_data/rice/rice_1.fq",
#file_read2 = "/home/cvcv/genorama/webserver/demo_data/rice/rice_2.fq",
#file_ass = "/gpfs/csic_users/res/cvcv/genorama/webserver/valid_results/Job_Spombe/ASSEMBLY_MAPPING/trinity/Trinity.fasta",
#input_type = "contigs",
#################### STEPS
FASTQC1 = True,
DUP = True,
TRIM = True,
CUTADAPT =True ,
#BLAT_UNIVEC = False,
#BLAT_ECOLI = False,
#BLAT_SCERE = False,
FASTQC2 = True,
#TRINITY = True,
# #TRINITY2 = False,
#ASSEMBLY_QUAL = True,
#CDHITEST = True,
# BOWTIE1 = False,
# BOWTIE2 = True,
#BLAT_CEGMA = True,
#BLAT_UNIREF = False,
#BLAT_NR = False,
#HMMER_CEGMA = False,
# HMMER_PFAMA = False,
# #HMMER_PFAMB = False,
# #BLAST_NR = False,
# BLASTPLUS_NR = False,
#INTERPROSCAN = True,
# BLAST2GO = False,
# #CUFFLINKS = False,
# RSEM = False,
# #CUFFDIFF = False,
# EXPRESS = False,
################### PARAMS
#DUP_DEREP1 = "on",
#DUP_DEREP2 = ,
#DUP_DEREP3 = ,
#DUP_DEREP4 = ,
#DUP_DEREP5 = ,
#DUP_NUM = "2",
#TRIM_QUAL_THRE = ,
#TRIM_MIN_LGTH = "40",
#TRIM_MAX_LGTH = ,
#TRIM_MIN_MEAN_QUAL = "20",
#TRIM_QUAL_5 = ,
#TRIM_QUAL_3 = "20",
#TRIM_QUAL_WIN = "1",
#TRIM_QUAL_STEP = "1",
#TRIM_5_BP = "12",
#TRIM_3_BP = ,
#TRIM_TAIL_5 = ,
#TRIM_TAIL_3 = "6",
#TRIM_CPLEX_MET = "dust",
#TRIM_CPLEX_THRE = "32",
CUTADAPT_ADAPT1="AAAAAAAAAA" ,
CUTADAPT_ADAPT2="ATCGATCGATC" ,
#TRIN_SS_LIB = "RF",
#TRIN_MIN_LGTH = "200",
#TRIN_SS_LIB = "RF",
####TRIN_REINF_DIST = "75",
####TRIN_MIN_KMER_COV = "1",
####TRIN_MIN_GLUE = "2",
# Iso and max path obsolete for trinity2014
#TRIN_MIN_ISO = "0.05",
#####TRIN_GLUE_FACT = "0.05",
#TRIN_GRP_DIST = "240",
#TRIN_JAC_CLIP = ,
#TRIN2_MIN_LGTH = "100",    
#BOW1_MAX_MIS = "2",
#BOW1_MAX_SUM = "70",
#BOW1_SEED_LGTH = "28",
#BOW1_MIN_INS = "0",
#BOW1_MAX_INS = "250",
#BOW1_MATES_ALI = "--fr",
#BOW1_NO_MAQ = ,
#BOW1_TRY_HARD= ,
#BOW2_MODE = "--end-to-end",
#BOW2_SPEED = "--sensitive",
#BOW2_MININS = "0",
#BOW2_MAXINS = "500"
)
